/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef uber_CONSTANTS_H
#define uber_CONSTANTS_H

#include "uber_types.h"

namespace Uber {

class uberConstants {
 public:
  uberConstants();

};

extern const uberConstants g_uber_constants;

} // namespace

#endif
