/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "uber_constants.h"

namespace Uber {

const uberConstants g_uber_constants;

uberConstants::uberConstants() {
}

} // namespace

